/**
 * Budget API
 * api для записей трат по бюджетам
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ilya_dt@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BudgetsWithSpendingsResponse from '../model/BudgetsWithSpendingsResponse';
import UpdateSpendingsBulkRequest from '../model/UpdateSpendingsBulkRequest';
import UpdateSpendingsErrorsResponse from '../model/UpdateSpendingsErrorsResponse';

/**
* Api service.
* @module api/ApiApi
* @version 1.0.0
*/
export default class ApiApi {

    /**
    * Constructs a new ApiApi. 
    * @alias module:api/ApiApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getBudgetsWithSpendings operation.
     * @callback module:api/ApiApi~getBudgetsWithSpendingsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BudgetsWithSpendingsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получение трат по всем бюджетам
     * Получение трат по всем бюджетам
     * @param {module:api/ApiApi~getBudgetsWithSpendingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BudgetsWithSpendingsResponse}
     */
    getBudgetsWithSpendings(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BudgetsWithSpendingsResponse;
      return this.apiClient.callApi(
        '/budgets/spendings', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateBudgetSpendings operation.
     * @callback module:api/ApiApi~updateBudgetSpendingsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Обновление расходов по бюджету
     * Обновление расходов по бюджету
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateSpendingsBulkRequest} [updateSpendingsBulkRequest] 
     * @param {module:api/ApiApi~updateBudgetSpendingsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateBudgetSpendings(opts, callback) {
      opts = opts || {};
      let postBody = opts['updateSpendingsBulkRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/budgets/spendings/bulk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
