/**
 * Budget API
 * api для записей трат по бюджетам
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ilya_dt@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Budget from './Budget';
import SpendingsByBudget from './SpendingsByBudget';

/**
 * The BudgetsWithSpendingsResponse model module.
 * @module model/BudgetsWithSpendingsResponse
 * @version 1.0.0
 */
class BudgetsWithSpendingsResponse {
    /**
     * Constructs a new <code>BudgetsWithSpendingsResponse</code>.
     * @alias module:model/BudgetsWithSpendingsResponse
     * @param budgets {Array.<module:model/Budget>} 
     * @param spendings {Array.<module:model/SpendingsByBudget>} 
     */
    constructor(budgets, spendings) { 
        
        BudgetsWithSpendingsResponse.initialize(this, budgets, spendings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, budgets, spendings) { 
        obj['budgets'] = budgets;
        obj['spendings'] = spendings;
    }

    /**
     * Constructs a <code>BudgetsWithSpendingsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BudgetsWithSpendingsResponse} obj Optional instance to populate.
     * @return {module:model/BudgetsWithSpendingsResponse} The populated <code>BudgetsWithSpendingsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BudgetsWithSpendingsResponse();

            if (data.hasOwnProperty('budgets')) {
                obj['budgets'] = ApiClient.convertToType(data['budgets'], [Budget]);
            }
            if (data.hasOwnProperty('spendings')) {
                obj['spendings'] = ApiClient.convertToType(data['spendings'], [SpendingsByBudget]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BudgetsWithSpendingsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BudgetsWithSpendingsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BudgetsWithSpendingsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['budgets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['budgets'])) {
                throw new Error("Expected the field `budgets` to be an array in the JSON data but got " + data['budgets']);
            }
            // validate the optional field `budgets` (array)
            for (const item of data['budgets']) {
                Budget.validateJSON(item);
            };
        }
        if (data['spendings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['spendings'])) {
                throw new Error("Expected the field `spendings` to be an array in the JSON data but got " + data['spendings']);
            }
            // validate the optional field `spendings` (array)
            for (const item of data['spendings']) {
                SpendingsByBudget.validateJSON(item);
            };
        }

        return true;
    }


}

BudgetsWithSpendingsResponse.RequiredProperties = ["budgets", "spendings"];

/**
 * @member {Array.<module:model/Budget>} budgets
 */
BudgetsWithSpendingsResponse.prototype['budgets'] = undefined;

/**
 * @member {Array.<module:model/SpendingsByBudget>} spendings
 */
BudgetsWithSpendingsResponse.prototype['spendings'] = undefined;






export default BudgetsWithSpendingsResponse;

