/**
 * Budget API
 * api для записей трат по бюджетам
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ilya_dt@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Spending from './Spending';

/**
 * The SpendingChange model module.
 * @module model/SpendingChange
 * @version 1.0.0
 */
class SpendingChange {
    /**
     * Constructs a new <code>SpendingChange</code>.
     * @alias module:model/SpendingChange
     * @param eventId {String} уникальный идентификатор события обновления
     * @param operation {module:model/SpendingChange.OperationEnum} 
     * @param spending {module:model/Spending} 
     */
    constructor(eventId, operation, spending) { 
        
        SpendingChange.initialize(this, eventId, operation, spending);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, eventId, operation, spending) { 
        obj['eventId'] = eventId;
        obj['operation'] = operation;
        obj['spending'] = spending;
    }

    /**
     * Constructs a <code>SpendingChange</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpendingChange} obj Optional instance to populate.
     * @return {module:model/SpendingChange} The populated <code>SpendingChange</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpendingChange();

            if (data.hasOwnProperty('eventId')) {
                obj['eventId'] = ApiClient.convertToType(data['eventId'], 'String');
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
            }
            if (data.hasOwnProperty('spending')) {
                obj['spending'] = Spending.constructFromObject(data['spending']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpendingChange</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpendingChange</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SpendingChange.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['eventId'] && !(typeof data['eventId'] === 'string' || data['eventId'] instanceof String)) {
            throw new Error("Expected the field `eventId` to be a primitive type in the JSON string but got " + data['eventId']);
        }
        // ensure the json data is a string
        if (data['operation'] && !(typeof data['operation'] === 'string' || data['operation'] instanceof String)) {
            throw new Error("Expected the field `operation` to be a primitive type in the JSON string but got " + data['operation']);
        }
        // validate the optional field `spending`
        if (data['spending']) { // data not null
          Spending.validateJSON(data['spending']);
        }

        return true;
    }


}

SpendingChange.RequiredProperties = ["eventId", "operation", "spending"];

/**
 * уникальный идентификатор события обновления
 * @member {String} eventId
 */
SpendingChange.prototype['eventId'] = undefined;

/**
 * @member {module:model/SpendingChange.OperationEnum} operation
 */
SpendingChange.prototype['operation'] = undefined;

/**
 * @member {module:model/Spending} spending
 */
SpendingChange.prototype['spending'] = undefined;





/**
 * Allowed values for the <code>operation</code> property.
 * @enum {String}
 * @readonly
 */
SpendingChange['OperationEnum'] = {

    /**
     * value: "create"
     * @const
     */
    "create": "create",

    /**
     * value: "update"
     * @const
     */
    "update": "update",

    /**
     * value: "delete"
     * @const
     */
    "delete": "delete"
};



export default SpendingChange;

