/**
 * Budget API
 * api для записей трат по бюджетам
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ilya_dt@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Spending from './Spending';

/**
 * The SpendingsByBudget model module.
 * @module model/SpendingsByBudget
 * @version 1.0.0
 */
class SpendingsByBudget {
    /**
     * Constructs a new <code>SpendingsByBudget</code>.
     * @alias module:model/SpendingsByBudget
     * @param budgetId {Number} 
     * @param spendings {Array.<module:model/Spending>} 
     */
    constructor(budgetId, spendings) { 
        
        SpendingsByBudget.initialize(this, budgetId, spendings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, budgetId, spendings) { 
        obj['budgetId'] = budgetId;
        obj['spendings'] = spendings;
    }

    /**
     * Constructs a <code>SpendingsByBudget</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpendingsByBudget} obj Optional instance to populate.
     * @return {module:model/SpendingsByBudget} The populated <code>SpendingsByBudget</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpendingsByBudget();

            if (data.hasOwnProperty('budgetId')) {
                obj['budgetId'] = ApiClient.convertToType(data['budgetId'], 'Number');
            }
            if (data.hasOwnProperty('spendings')) {
                obj['spendings'] = ApiClient.convertToType(data['spendings'], [Spending]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpendingsByBudget</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpendingsByBudget</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SpendingsByBudget.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['spendings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['spendings'])) {
                throw new Error("Expected the field `spendings` to be an array in the JSON data but got " + data['spendings']);
            }
            // validate the optional field `spendings` (array)
            for (const item of data['spendings']) {
                Spending.validateJSON(item);
            };
        }

        return true;
    }


}

SpendingsByBudget.RequiredProperties = ["budgetId", "spendings"];

/**
 * @member {Number} budgetId
 */
SpendingsByBudget.prototype['budgetId'] = undefined;

/**
 * @member {Array.<module:model/Spending>} spendings
 */
SpendingsByBudget.prototype['spendings'] = undefined;






export default SpendingsByBudget;

