/**
 * Budget API
 * api для записей трат по бюджетам
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ilya_dt@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateSpendingsError from './UpdateSpendingsError';

/**
 * The UpdateSpendingsErrorsResponse model module.
 * @module model/UpdateSpendingsErrorsResponse
 * @version 1.0.0
 */
class UpdateSpendingsErrorsResponse {
    /**
     * Constructs a new <code>UpdateSpendingsErrorsResponse</code>.
     * @alias module:model/UpdateSpendingsErrorsResponse
     * @param errors {Array.<module:model/UpdateSpendingsError>} 
     */
    constructor(errors) { 
        
        UpdateSpendingsErrorsResponse.initialize(this, errors);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, errors) { 
        obj['errors'] = errors;
    }

    /**
     * Constructs a <code>UpdateSpendingsErrorsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateSpendingsErrorsResponse} obj Optional instance to populate.
     * @return {module:model/UpdateSpendingsErrorsResponse} The populated <code>UpdateSpendingsErrorsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateSpendingsErrorsResponse();

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [UpdateSpendingsError]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateSpendingsErrorsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateSpendingsErrorsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateSpendingsErrorsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['errors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['errors'])) {
                throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
            }
            // validate the optional field `errors` (array)
            for (const item of data['errors']) {
                UpdateSpendingsError.validateJSON(item);
            };
        }

        return true;
    }


}

UpdateSpendingsErrorsResponse.RequiredProperties = ["errors"];

/**
 * @member {Array.<module:model/UpdateSpendingsError>} errors
 */
UpdateSpendingsErrorsResponse.prototype['errors'] = undefined;






export default UpdateSpendingsErrorsResponse;

