/**
 * Budget API
 * api для записей трат по бюджетам
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ilya_dt@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SpendingChange from './SpendingChange';

/**
 * The UpdateSpendingsBulkRequest model module.
 * @module model/UpdateSpendingsBulkRequest
 * @version 1.0.0
 */
class UpdateSpendingsBulkRequest {
    /**
     * Constructs a new <code>UpdateSpendingsBulkRequest</code>.
     * @alias module:model/UpdateSpendingsBulkRequest
     * @param updates {Array.<module:model/SpendingChange>} 
     */
    constructor(updates) { 
        
        UpdateSpendingsBulkRequest.initialize(this, updates);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, updates) { 
        obj['updates'] = updates;
    }

    /**
     * Constructs a <code>UpdateSpendingsBulkRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateSpendingsBulkRequest} obj Optional instance to populate.
     * @return {module:model/UpdateSpendingsBulkRequest} The populated <code>UpdateSpendingsBulkRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateSpendingsBulkRequest();

            if (data.hasOwnProperty('updates')) {
                obj['updates'] = ApiClient.convertToType(data['updates'], [SpendingChange]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateSpendingsBulkRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateSpendingsBulkRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateSpendingsBulkRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['updates']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['updates'])) {
                throw new Error("Expected the field `updates` to be an array in the JSON data but got " + data['updates']);
            }
            // validate the optional field `updates` (array)
            for (const item of data['updates']) {
                SpendingChange.validateJSON(item);
            };
        }

        return true;
    }


}

UpdateSpendingsBulkRequest.RequiredProperties = ["updates"];

/**
 * @member {Array.<module:model/SpendingChange>} updates
 */
UpdateSpendingsBulkRequest.prototype['updates'] = undefined;






export default UpdateSpendingsBulkRequest;

