/**
 * Budget API
 * api для записей трат по бюджетам
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ilya_dt@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateSpendingsError model module.
 * @module model/UpdateSpendingsError
 * @version 1.0.0
 */
class UpdateSpendingsError {
    /**
     * Constructs a new <code>UpdateSpendingsError</code>.
     * @alias module:model/UpdateSpendingsError
     * @param eventId {String} 
     * @param error {String} 
     */
    constructor(eventId, error) { 
        
        UpdateSpendingsError.initialize(this, eventId, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, eventId, error) { 
        obj['eventId'] = eventId;
        obj['error'] = error;
    }

    /**
     * Constructs a <code>UpdateSpendingsError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateSpendingsError} obj Optional instance to populate.
     * @return {module:model/UpdateSpendingsError} The populated <code>UpdateSpendingsError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateSpendingsError();

            if (data.hasOwnProperty('eventId')) {
                obj['eventId'] = ApiClient.convertToType(data['eventId'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateSpendingsError</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateSpendingsError</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateSpendingsError.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['eventId'] && !(typeof data['eventId'] === 'string' || data['eventId'] instanceof String)) {
            throw new Error("Expected the field `eventId` to be a primitive type in the JSON string but got " + data['eventId']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}

UpdateSpendingsError.RequiredProperties = ["eventId", "error"];

/**
 * @member {String} eventId
 */
UpdateSpendingsError.prototype['eventId'] = undefined;

/**
 * @member {String} error
 */
UpdateSpendingsError.prototype['error'] = undefined;






export default UpdateSpendingsError;

