/**
 * Budget API
 * api для записей трат по бюджетам
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ilya_dt@proton.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Budget from './model/Budget';
import BudgetsWithSpendingsResponse from './model/BudgetsWithSpendingsResponse';
import Money from './model/Money';
import Spending from './model/Spending';
import SpendingChange from './model/SpendingChange';
import SpendingsByBudget from './model/SpendingsByBudget';
import UpdateSpendingsBulkRequest from './model/UpdateSpendingsBulkRequest';
import UpdateSpendingsError from './model/UpdateSpendingsError';
import UpdateSpendingsErrorsResponse from './model/UpdateSpendingsErrorsResponse';
import ApiApi from './api/ApiApi';


/**
* api для записей трат по бюджетам.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BudgetApi = require('index'); // See note below*.
* var xxxSvc = new BudgetApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BudgetApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BudgetApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BudgetApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Budget model constructor.
     * @property {module:model/Budget}
     */
    Budget,

    /**
     * The BudgetsWithSpendingsResponse model constructor.
     * @property {module:model/BudgetsWithSpendingsResponse}
     */
    BudgetsWithSpendingsResponse,

    /**
     * The Money model constructor.
     * @property {module:model/Money}
     */
    Money,

    /**
     * The Spending model constructor.
     * @property {module:model/Spending}
     */
    Spending,

    /**
     * The SpendingChange model constructor.
     * @property {module:model/SpendingChange}
     */
    SpendingChange,

    /**
     * The SpendingsByBudget model constructor.
     * @property {module:model/SpendingsByBudget}
     */
    SpendingsByBudget,

    /**
     * The UpdateSpendingsBulkRequest model constructor.
     * @property {module:model/UpdateSpendingsBulkRequest}
     */
    UpdateSpendingsBulkRequest,

    /**
     * The UpdateSpendingsError model constructor.
     * @property {module:model/UpdateSpendingsError}
     */
    UpdateSpendingsError,

    /**
     * The UpdateSpendingsErrorsResponse model constructor.
     * @property {module:model/UpdateSpendingsErrorsResponse}
     */
    UpdateSpendingsErrorsResponse,

    /**
    * The ApiApi service constructor.
    * @property {module:api/ApiApi}
    */
    ApiApi
};
